version: 2.1
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  release_builds:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/build-release.yml

  # setup:
  #   executor: continuation/default
  #   steps:
  #     - checkout
  #     - run:
  #         name: Generate config
  #         command: cd .circleci && ./make.sh
  #     - continuation/continue:
  #         configuration_path: ./.circleci/config.gen.yml

setup: true
workflows:
  setup:
    jobs:
      - setup
