version: 2.1
# orbs:
#   continuation: circleci/continuation@0.1.2

# jobs:
#   setup:
#     executor: continuation/default
#     steps:
#       - checkout
#       - run:
#           name: Generate config
#           command: cd .circleci && ./make.sh
#       - continuation/continue:
#           configuration_path: ./.circleci/config.gen.yml

# setup: true
# workflows:
#   setup:
#     jobs:
#       - setup

jobs:
  mac_test:
    macos:
      xcode: 12.5.1

    resource_class: macos.x86.medium.gen2

    steps:
      - checkout
      - run:
          name: Install command dependencies
          command: |
            curl -sSL https://get.haskellstack.org/ | sh
            HOMEBREW_NO_AUTO_UPDATE=1 brew install wget llvm
            make -C hs install-mo
            echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> /Users/distiller/.bash_profile
            export LDFLAGS="-L/usr/local/opt/llvm/lib"
            export CPPFLAGS="-I/usr/local/opt/llvm/include"
      - run:
          name: Compile
          command: make -C hs hs-build

workflows:
  build:
    jobs:
      - mac_test
