version: 2.1
# orbs:
#   continuation: circleci/continuation@0.1.2

# jobs:
#   setup:
#     executor: continuation/default
#     steps:
#       - checkout
#       - run:
#           name: Generate config
#           command: cd .circleci && ./make.sh
#       - continuation/continue:
#           configuration_path: ./.circleci/config.gen.yml

# setup: true
# workflows:
#   setup:
#     jobs:
#       - setup

orbs:
  windows: circleci/windows@4.1.1

jobs:
  mac_build:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Install command dependencies
          command: |
            curl -sSL https://get.haskellstack.org/ | sh
            HOMEBREW_NO_AUTO_UPDATE=1 brew install wget llvm
            make -C hs install-mo
            echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> /Users/distiller/.bash_profile
            export LDFLAGS="-L/usr/local/opt/llvm/lib"
            export CPPFLAGS="-I/usr/local/opt/llvm/include"
      - run:
          name: Compile
          command: make -C hs hs-build
  windows_build:
    executor:
      name: windows/default
    steps:
      - checkout
      # - run:
      #     name: Install command dependencies
      #     command: |
      #       Invoke-WebRequest "https://get.haskellstack.org/stable/windows-x86_64.zip" -OutFile "stack.zip"
      #       Expand-Archive "stack.zip" -DestinationPath "stack/"
      #       Copy-Item "stack\stack.exe" -Destination "$env:APPDATA\local\bin\stack.exe"
      - run:
          name: Install command dependencies
          shell: bash.exe
          command: |
            curl -sSL https://get.haskellstack.org/ | bash
            choco install make wget
      - run:
          name: Compile
          shell: bash.exe
          command: make -C hs hs-build


workflows:
  build:
    jobs:
      - hold_build_all_os:
          name: Build for all operating systems
          type: approval

      - windows_build:
          requires:
            - hold_build_all_os

      - mac_build:
          requires:
            - hold_build_all_os
