version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.2

workflows:
  run_release_builds:
    jobs:
      - run_release_builds

jobs:
  run_release_builds:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/release-builds/config.yml

  # setup:
  #   executor: continuation/default
  #   steps:
  #     - checkout
  #     - run:
  #         name: Generate config
  #         command: cd .circleci && ./make.sh
  #     - continuation/continue:
  #         configuration_path: ./.circleci/config.gen.yml

# workflows:
#   setup:
#     jobs:
#       - setup
