version: 2.1
# orbs:
#   continuation: circleci/continuation@0.1.2

# jobs:
#   setup:
#     executor: continuation/default
#     steps:
#       - checkout
#       - run:
#           name: Generate config
#           command: cd .circleci && ./make.sh
#       - continuation/continue:
#           configuration_path: ./.circleci/config.gen.yml

# setup: true
# workflows:
#   setup:
#     jobs:
#       - setup

jobs:
  mac_test:
    macos:
      xcode: 12.5.1

    steps:
      - checkout
      - run: wget -qO- https://get.haskellstack.org/ | sh
      - run: make -C hs hs-build
