version: 2.1
# orbs:
#   continuation: circleci/continuation@0.1.2

# jobs:
#   setup:
#     executor: continuation/default
#     steps:
#       - checkout
#       - run:
#           name: Generate config
#           command: cd .circleci && ./make.sh
#       - continuation/continue:
#           configuration_path: ./.circleci/config.gen.yml

# setup: true
# workflows:
#   setup:
#     jobs:
#       - setup

orbs:
  windows: circleci/windows@4.1.1

jobs:
  linux_build:
    docker:
      - image: haskell:9.0.2
    steps:
      - checkout
      - run: 
          name: Compile
          command: |
            # Compile
            cd hs
            make hs-build

            # Gather artifacts
            REACH="$(stack exec -- which reach)"
            REACHPC="$(stack exec -- which reachpc)"
            REACHC="$(stack exec -- which reachc)"
            strip "$REACH" "$REACHPC" "$REACHC"
            mkdir -p /tmp/artifacts
            mv "$REACH" "$REACHPC" "$REACHC" /tmp/artifacts
            for art in /tmp/artifacts/*; do gzip "$art"; done
      - store_artifacts:
          path: /tmp/artifacts

  mac_build:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Compile
          command: |
            # Install command dependencies
            curl -sSL https://get.haskellstack.org/ | sh
            HOMEBREW_NO_AUTO_UPDATE=1 brew install wget

            # Compile
            cd hs
            make hs-build
          
            # Gather artifacts
            REACH="$(stack exec -- which reach)"
            REACHPC="$(stack exec -- which reachpc)"
            REACHC="$(stack exec -- which reachc)"
            strip "$REACH" "$REACHPC" "$REACHC"
            mkdir -p /tmp/artifacts
            mv "$REACH" "$REACHPC" "$REACHC" /tmp/artifacts
            for art in /tmp/artifacts/*; do gzip "$art"; done
      - store_artifacts:
          path: /tmp/artifacts

  windows_build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Compile
          shell: bash.exe
          command: |
            # Install command dependencies
            curl -sSL https://get.haskellstack.org/ | bash
            choco install make wget

            # Compile
            cd hs
            make hs-build
            
            # Gather artifacts
            REACH="$(stack exec -- which reach)"
            REACHPC="$(stack exec -- which reachpc)"
            REACHC="$(stack exec -- which reachc)"
            mkdir -p /c/tmp/artifacts
            mv "$REACH" "$REACHC" "$REACHPC" /c/tmp/artifacts
            for art in /c/tmp/artifacts/*; do 7z a "$art".gz "$art"; done
      - store_artifacts:
          path: /tmp/artifacts

parameters:
  run_release_builds:
    type: boolean
    default: true

workflows:
  release_builds:
    when: << pipeline.parameters.run_release_builds >>
    jobs:
      - windows_build
      - mac_build
      - linux_build
